# Generated by Django 4.0.8 on 2023-04-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoggingApi', '0002_demdailydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='demdailydata',
            name='trip',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
