# Generated by Django 4.0.8 on 2023-05-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoggingApi', '0003_demdailydata_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodDailyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('meal_type', models.CharField(max_length=200)),
                ('meal_qty', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('junk', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
