# Generated by Django 4.0.8 on 2023-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataLoggingApi', '0005_fooddailydata_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingDemCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('primary_category', models.CharField(max_length=200)),
                ('secondary_category', models.CharField(max_length=200)),
            ],
        ),
    ]
