# Generated by Django 4.0.8 on 2023-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
                ('document_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(max_length=200)),
                ('document_remarks', models.CharField(max_length=200)),
                ('document_path', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
            ],
        ),
    ]
