# Generated by Django 3.2.15 on 2023-09-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocManager', '0003_docma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docma',
            name='cat1',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='docma',
            name='cat2',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='docma',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
