# Generated by Django 3.2.15 on 2023-09-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocManager', '0005_doc_holder_doc_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='docma',
        ),
    ]
