# Generated by Django 4.0.8 on 2023-09-16 17:45

import DocManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocManager', '0007_docma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docma',
            name='document_back',
            field=models.FileField(default=None, upload_to=DocManager.models.upload_setup_back),
        ),
    ]
