# Generated by Django 4.0.8 on 2023-09-16 17:49

import DocManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocManager', '0008_alter_docma_document_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docma',
            name='document_back',
            field=models.FileField(blank=True, default=None, upload_to=DocManager.models.upload_setup_back),
        ),
    ]
