# Generated by Django 4.0.8 on 2023-09-17 01:51

import DocManager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocManager', '0009_alter_docma_document_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docma',
            name='document_back',
            field=models.FileField(blank=True, default='default.png', upload_to=DocManager.models.upload_setup_back),
        ),
    ]
